name = "rin-server"
main = "server/src/_worker.ts"
compatibility_date = "2025-10-18"
compatibility_flags = ["nodejs_compat"]  # <<< 保留，启用 Node 内置模块兼容

# <<< 新增，解决 @sinclair/typebox 编译报错
[build]
external = ["@sinclair/typebox"]

[vars]
FRONTEND_URL = "http://localhost:5173"
S3_FOLDER = "images/"
S3_CACHE_FOLDER = "cache/"
S3_REGION = "auto"
S3_ENDPOINT = "<YourS3Endpoint>"
S3_ACCESS_HOST = "<YourS3AccessHost>"
S3_BUCKET = "<YourS3BucketName>"
S3_FORCE_PATH_STYLE = "false"
WEBHOOK_URL = "https://<YourWebhookURL>"
RSS_TITLE = "Rin Development Environment"
RSS_DESCRIPTION = "Development Environment"

[[d1_databases]]
binding = "DB"
database_name = "rin"
database_id = "YourDatabaseID"

[triggers]
crons = ["*/20 * * * *"]
