name = "rin-server"
main = "server/src/_worker.ts"   # Worker 入口文件
compatibility_date = "2025-10-17"
compatibility_flags = ["nodejs_compat"]  # <<< Wrangler v4 兼容 Node.js

[vars]
FRONTEND_URL = "http://localhost:5173"
S3_FOLDER = "images/"
S3_CACHE_FOLDER = "cache/"
S3_REGION = "auto"
S3_ENDPOINT = "<YourS3Endpoint>"
S3_ACCESS_HOST = "<YourS3AccessHost>"
S3_BUCKET = "<YourS3BucketName>"
S3_FORCE_PATH_STYLE = "false"
WEBHOOK_URL = "https://<YourWebhookURL>"
RSS_TITLE = "Rin Development Environment"
RSS_DESCRIPTION = "Development Environment"

[[d1_databases]]
binding = "DB"
database_name = "rin"
database_id = "cb3efb10-abfb-4d70-ad5a-187b2d7c6fef"

[triggers]
crons = ["*/20 * * * *"]
